#!/usr/bin/env python3
"""Build a multi-pack SFZ: each pack folder plays on the same keys, and a keyswitch picks the pack.

    packs/                     python3 packs_to_sfz.py packs/ dj_keys.sfz --first-key 36
      songA/  kick.wav ...     -> keys 36, 37, 38 ... trigger songA's files
      songB/  loop1.wav ...    -> press a keyswitch (default: the keys just below 36) and the
      songC/  ...                 same keys now trigger songB's files

Play it in sfizz or Sforzando (both free) or any other SFZ player. Sample paths in the output
are relative to the .sfz file, so keep the .sfz and the pack folders together.

Opcodes used (see sfzformat.com): sw_lokey, sw_hikey, sw_last, sw_default, sw_label, key,
loop_mode, loop_start, loop_end, ampeg_release.
"""
import argparse
import sys
from pathlib import Path

import packlib

LOOP_MODES = {"loop": "loop_continuous", "hold": "no_loop", "oneshot": "one_shot"}


def build_sfz(root, out_path, first_key=36, white_keys_only=False, mode="loop",
              switch_first_key=None, release=0.05):
    packs = packlib.list_packs(root)
    slots = max(len(packlib.list_samples(p)) for p in packs)
    keys = packlib.playable_keys(first_key, slots, white_keys_only)
    switches = packlib.switch_keys(switch_first_key, first_key, keys, len(packs))
    out_dir = Path(out_path).resolve().parent

    lines = [
        "// Generated by packs_to_sfz.py",
        f"// Playable keys: {keys[0]}..{keys[-1]} (MIDI note numbers)",
        f"// Pack keyswitches: {', '.join(f'{k} = {p.name}' for k, p in zip(switches, packs))}",
        "",
        "<control>",
        "",
        "<global>",
        f"sw_lokey={switches[0]}",
        f"sw_hikey={switches[-1]}",
        f"sw_default={switches[0]}",
        f"ampeg_release={release}",
        "",
    ]
    for switch_key, pack in zip(switches, packs):
        lines += ["<group>", f"sw_last={switch_key}", f"sw_label={pack.name}"]
        for key, sample in zip(keys, packlib.list_samples(pack)):
            region = f"<region> sample={packlib.relative_posix(sample, out_dir)} key={key} loop_mode={LOOP_MODES[mode]}"
            frames = packlib.wav_frames(sample)
            if mode == "loop" and frames:
                region += f" loop_start=0 loop_end={frames - 1}"
            lines.append(region)
        lines.append("")

    Path(out_path).write_text("\n".join(lines), encoding="utf-8")
    return {"packs": [p.name for p in packs], "keys": keys, "switches": switches}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("packs_dir", help="folder whose sub-folders are the packs")
    parser.add_argument("output", help="the .sfz file to write (keep it next to the packs folder)")
    parser.add_argument("--first-key", type=int, default=36, help="MIDI note of the first sample (default 36)")
    parser.add_argument("--switch-first-key", type=int, default=None,
                        help="MIDI note of the first pack keyswitch (default: just below --first-key)")
    parser.add_argument("--white-keys-only", action="store_true", help="skip black keys for samples")
    parser.add_argument("--mode", choices=sorted(LOOP_MODES), default="loop",
                        help="loop = repeat while held (default), hold = play once, stop on release, "
                             "oneshot = always play to the end")
    parser.add_argument("--release", type=float, default=0.05, help="release time in seconds (default 0.05)")
    args = parser.parse_args(argv)

    try:
        info = build_sfz(args.packs_dir, args.output, args.first_key, args.white_keys_only, args.mode,
                         args.switch_first_key, args.release)
    except (ValueError, FileNotFoundError) as err:
        print(f"error: {err}", file=sys.stderr)
        return 1
    print(f"Wrote {args.output}: {len(info['packs'])} packs, keys {info['keys'][0]}..{info['keys'][-1]}")
    for key, name in zip(info["switches"], info["packs"]):
        print(f"  keyswitch {key:3d} -> {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
