# name=Trap Metal Kit
"""Trap Metal Kit: ONE FL Studio script, ONE MIDI input, everything on it.

FL Studio only runs one controller script per MIDI input, and this kit has four (DJ decks, vocal mixer setup,
plugin probe, pink theme). This file holds all four, so you assign it once and get the lot.

THIS FILE IS GENERATED by tools/build_fl_bundle.py from the four device_*.py files beside it. Edit the CONFIG block
just below to change keys / turn parts off. To change anything deeper, edit the source script and rebuild (a rebuild
resets this CONFIG block). Build id: 96b18701

Default key map (FL names note 60 "C5"; every number here is a MIDI note):

    36-67   launch Performance Mode clips: 4 decks (playlist tracks 1-4) x 8 clips       (C3 - G5)
    68-71   stop deck 1-4                                                                (G#5 - B5)
    72      PROBE   list every plugin in the mixer and the parameters FL can automate    (C6)  read-only
    73      AUDIT   check Nectar 4 / Ozone 12 / a distortion are on the right inserts    (C#6) read-only
    74      SETUP   build the vocal mixer (names, colours, routing, sends, arm the lead) (D6)  press twice
    75      REPAINT paint channels, mixer, playlist and patterns pink / purple / red     (D#6) press twice
    mod wheel (CC 1)  crossfades deck 1 against deck 2 on mixer inserts 10 and 11

SETUP and REPAINT change your project, so they only run if you press the key a second time within a few seconds.
Everything it does is reported in View > Script output (and under the controller's tab in Options > MIDI Settings).

Install: python3 tools/install_fl_studio.py   then see docs/00-fl-studio-quickstart.md.
Tested against stubs of the FL modules and checked against Image-Line's published API stubs; not run inside FL Studio.
"""
import time
import traceback
import types

# ======================================================================================================== CONFIG
# Turn a part off by setting it to False.
ENABLED = {
    "TrapDJ": True,        # keys 36-71 launch clips; mod wheel crossfades
    "VocalSetup": True,    # SETUP / AUDIT keys
    "PluginProbe": True,   # PROBE key
    "PinkTheme": True,     # pink painting at start-up + REPAINT key
}

# Change any setting of any part: "Part": {"SETTING": value}. A setting must exist in that part's source script
# (see its top-of-file constants); a typo is reported in Script output and ignored.
OVERRIDES = {
    # Decks sit on mixer inserts 10 and 11 so the mod-wheel crossfader never touches the vocal inserts (1-8).
    "TrapDJ": {"DECK_A_MIXER": 10, "DECK_B_MIXER": 11},
    # The four command keys sit directly above the DJ block, inside what a 49/61/88-key keyboard can play.
    "PluginProbe": {"PROBE_NOTE": 72},
    "VocalSetup": {"AUDIT_NOTE": 73, "SETUP_NOTE": 74},
    "PinkTheme": {"REPAINT_NOTE": 75},      # add "PAINT_ON_START": False to stop it painting when FL starts
}

# SETUP and REPAINT only run on the second press within this many seconds. 0 = run on the first press.
CONFIRM_SECONDS = 3.0
# ================================================================================================ end of CONFIG

SECTION_ORDER = ["TrapDJ", "VocalSetup", "PluginProbe", "PinkTheme"]
GUARDED = {   # part -> (setting holding the key, what pressing it does)
    "VocalSetup": ("SETUP_NOTE", "rebuild mixer inserts 1-8 as the vocal layout"),
    "PinkTheme": ("REPAINT_NOTE", "repaint every channel, mixer insert, playlist track and pattern"),
}

BUILD = "96b18701"

_SOURCES = {

# ======== embedded verbatim from fl-studio/device_TrapDJ.py ========
'TrapDJ': r'''# name: Trap DJ Keys
"""FL Studio MIDI-controller script: play your keyboard like a DJ deck.

Every key launches one Performance Mode clip in the Playlist, so each track is a "deck"
and each block on that track is a different song/loop/stem. Pressing another key on the
same row blends the next piece in on the beat. A CC (mod wheel by default) crossfades two
mixer tracks.

Layout (FIRST_NOTE = 36 by default, i.e. C3 in FL's naming, where middle C = 60 = C5):

    keys 36..43   -> playlist track 1, blocks 0..7     (row 1 / deck 1)
    keys 44..51   -> playlist track 2, blocks 0..7     (row 2 / deck 2)
    ...           -> ROWS rows in total
    next ROWS keys-> stop the live clips on track 1..ROWS

Setup:
    1. Copy this file to
         Documents/Image-Line/FL Studio/Settings/Hardware/TrapDJ/device_TrapDJ.py
    2. FL Studio > Options > MIDI Settings: pick your keyboard as an input, set
       Controller type to "Trap DJ Keys", and give it a port number.
    3. Playlist: switch on Performance mode (Playlist menu > Performance mode, or Ctrl+P). Put
       your audio clips on the tracks inside the Performance Zone (left of the Start marker; only
       clips there can be triggered) and add Live block markers. Then right-click each track
       header > Performance settings: set "Trigger sync" to a bar value and "Press" to Latch
       (or Hold & stop). Those settings only appear while Performance mode is on.
    4. Route playlist track 1 -> mixer insert DECK_A_MIXER and track 2 -> DECK_B_MIXER
       if you want the crossfader.

API notes: playlist.triggerLiveClip, the midi.TLC_* flags and the OnNoteOn/OnControlChange
callbacks come from the FL Studio MIDI scripting manual. Block numbers are treated as
0-based and track numbers as 1-based (see TRACK_BASE); if your clips land one off, change
TRACK_BASE. This script has been tested against stubs of the FL modules, not inside FL Studio.
"""
import math

import midi
import mixer
import playlist

FIRST_NOTE = 36     # MIDI note of the first clip slot
COLUMNS = 8         # blocks (songs/loops) per deck row
ROWS = 4            # number of deck rows (playlist tracks)
TRACK_BASE = 1      # playlist track number of row 1

# Trigger-sync source: midi.TLC_TrackSnap uses each track's own "Trigger sync" setting,
# midi.TLC_GlobalSnap uses FL's global snap, midi.TLC_NoSnap fires immediately.
SNAP_FLAG = midi.TLC_TrackSnap

XFADE_CC = 1        # mod wheel. Set to None to disable the crossfader.
DECK_A_MIXER = 1    # mixer insert that carries deck A (left side of the crossfader)
DECK_B_MIXER = 2    # mixer insert that carries deck B (right side)
UNITY_VOLUME = 0.8  # FL's normalised mixer volume for 0 dB


def stop_first_note():
    """MIDI note of the first stop key. Worked out on demand so FIRST_NOTE / ROWS / COLUMNS can be changed later."""
    return FIRST_NOTE + ROWS * COLUMNS


def slot_for_note(note):
    """Return ('play', track, block), ('stop', track) or None for a MIDI note."""
    index = note - FIRST_NOTE
    if 0 <= index < ROWS * COLUMNS:
        return ("play", TRACK_BASE + index // COLUMNS, index % COLUMNS)
    stop_first = stop_first_note()
    if stop_first <= note < stop_first + ROWS:
        return ("stop", TRACK_BASE + (note - stop_first))
    return None


def crossfade_gains(position):
    """Equal-power crossfade. position 0.0 = all deck A, 1.0 = all deck B."""
    position = min(max(position, 0.0), 1.0)
    return math.cos(position * math.pi / 2), math.sin(position * math.pi / 2)


def OnInit():
    stop_first = stop_first_note()
    print("Trap DJ Keys: notes %d-%d launch clips, %d-%d stop decks"
          % (FIRST_NOTE, stop_first - 1, stop_first, stop_first + ROWS - 1))
    try:
        if not playlist.getPerformanceModeState():
            print("Trap DJ Keys: Performance Mode is off - enable it or clips will not launch")
    except AttributeError:
        pass  # getPerformanceModeState needs a recent FL Studio (API 21+)


def OnNoteOn(event):
    if event.data2 == 0:  # some keyboards send note-off as note-on with velocity 0
        return
    action = slot_for_note(event.data1)
    if action is None:
        return  # not one of ours; let FL play the note normally
    if action[0] == "play":
        _, track, block = action
        playlist.triggerLiveClip(track, block, SNAP_FLAG)
    else:
        _, track = action
        playlist.triggerLiveClip(track, -1, midi.TLC_Fill | SNAP_FLAG)
    event.handled = True


def OnNoteOff(event):
    if slot_for_note(event.data1) is not None:
        event.handled = True  # swallow the release so it does not reach the channel rack


def OnControlChange(event):
    if XFADE_CC is None or event.data1 != XFADE_CC:
        return
    gain_a, gain_b = crossfade_gains(event.data2 / 127.0)
    mixer.setTrackVolume(DECK_A_MIXER, UNITY_VOLUME * gain_a)
    mixer.setTrackVolume(DECK_B_MIXER, UNITY_VOLUME * gain_b)
    event.handled = True
''',

# ======== embedded verbatim from fl-studio/device_VocalSetup.py ========
'VocalSetup': r'''# name: Vocal Session Setup
"""FL Studio MIDI-controller script: builds a vocal recording/mixing layout in the Mixer with one key press.

Press SETUP_NOTE (default 126 = F#10 in FL's note names) on the assigned MIDI input and it will, on mixer inserts FIRST_INSERT and up:

    * name and colour each insert (pink / purple / red palette to match device_PinkTheme.py)
    * route every vocal insert to the VOX BUS insert (and switch off its direct route to Master)
    * add send routes from every vocal insert to REVERB and DELAY at set levels
    * arm the lead vocal insert for recording (only if it is not armed already)

    VOX MAIN, VOX DBL L, VOX DBL R, ADLIBS, SCREAMS  ->  VOX BUS  ->  Master
                        each also sends to  REVERB and DELAY  ->  Master

What FL's scripting API cannot do: load plugins into slots, pick the audio input, or start recording. So after
running this, (1) pick the audio input on VOX MAIN's Input selector, (2) load your saved vocal-chain preset into
the inserts (save one once with a mixer track's preset menu), (3) press record. docs/07 walks through it.

Press AUDIT_NOTE (default 125) any time to CHECK THE CHAIN: it lists the plugin in every slot of the vocal inserts
and the Master, and says whether the ones you expect are there (Nectar 4 on VOX MAIN, Ozone 12 on Master, a
distortion such as Unison Mangler on SCREAMS). It only reads; it never loads or changes a plugin.

Safety: it refuses to touch an insert that you have already renamed to something else, and says so in the
script output (View > Script output). Set FORCE = True to override. Pressing the key again on inserts it named
itself is fine.

API used: mixer.setTrackName / setTrackColor / setRouteTo / setRouteToLevel (FL API 36+) / afterRoutingChanged /
isTrackArmed / armTrack, plus plugins.isValid / getPluginName for the audit. Tested against stubs of the FL modules,
not inside FL Studio.
"""
import re

import mixer

try:
    import plugins
except ImportError:  # only if FL's plugins module is unavailable
    plugins = None

SETUP_NOTE = 126
AUDIT_NOTE = 125
FORCE = False
FIRST_INSERT = 1
MASTER = 0

# (name, (r, g, b), role). Colours match device_PinkTheme.py.
LAYOUT = [
    ("VOX MAIN", (255, 20, 147), "vocal"),
    ("VOX DBL L", (255, 77, 166), "vocal"),
    ("VOX DBL R", (255, 77, 166), "vocal"),
    ("ADLIBS", (155, 48, 255), "vocal"),
    ("SCREAMS", (224, 30, 75), "vocal"),
    ("VOX BUS", (233, 30, 140), "bus"),
    ("REVERB", (91, 33, 182), "fx"),
    ("DELAY", (91, 33, 182), "fx"),
]
SEND_LEVELS = {"REVERB": 0.45, "DELAY": 0.35}   # 0.8 is FL's default (0 dB) send level
ARM_TRACK = "VOX MAIN"

MAX_SLOTS = 10
MASTER_NAME = "MASTER"
# Plugins each insert should carry. Each entry is a group of alternatives (lower-case substrings of the plugin
# name); the group is satisfied if ANY alternative is found in ANY slot of that insert.
EXPECTED = {
    "VOX MAIN": [("nectar",)],                                              # Nectar 4: Vocal Assistant / vocal chain
    "SCREAMS": [("mangler", "trash", "decapitator", "saturn", "nectar")],   # something that distorts
    MASTER_NAME: [("ozone",)],                                              # Ozone 12: Master Assistant / limiter
}
HINTS = [
    "VOX MAIN: load Nectar 4, open Vocal Assistant, pick a target, then set EQ / intensity / width and reverb/delay.",
    "SCREAMS / ADLIBS: add Unison Mangler (or Nectar's Saturation module if you own Nectar Advanced) for the grit.",
    "MASTER: load Ozone 12, open Master Assistant, choose the Trap / Hyperpop / Metal target, loudness target and "
    "Analysis Time on your loudest section, press Analyze while the chorus plays.",
    "Before you export: turn Ozone's Gain Match OFF, then run tools/master_batch.py measure on the file.",
]

_DEFAULT_NAME = re.compile(r"^\s*(insert\s*\d*)?\s*$", re.IGNORECASE)


def rgb_to_fl(r, g, b):
    return (b << 16) | (g << 8) | r


def index_of(name):
    for offset, (layout_name, _, _) in enumerate(LAYOUT):
        if layout_name == name:
            return FIRST_INSERT + offset
    raise KeyError(name)


def blocked_inserts():
    """Inserts in the layout range that carry a name the user chose (not a default, not one of ours)."""
    ours = {name for name, _, _ in LAYOUT}
    blocked = []
    for offset in range(len(LAYOUT)):
        index = FIRST_INSERT + offset
        current = mixer.getTrackName(index)
        if current not in ours and not _DEFAULT_NAME.match(current or ""):
            blocked.append((index, current))
    return blocked


def setup():
    if FIRST_INSERT + len(LAYOUT) > mixer.trackCount() - 1:
        print("Vocal Session Setup: not enough mixer inserts for the layout")
        return False
    blocked = blocked_inserts()
    if blocked and not FORCE:
        print("Vocal Session Setup: NOT run - these inserts already have names of your own: "
              + ", ".join("%d '%s'" % pair for pair in blocked) + ". Rename them or set FORCE = True.")
        return False

    for offset, (name, rgb, _) in enumerate(LAYOUT):
        mixer.setTrackName(FIRST_INSERT + offset, name)
        mixer.setTrackColor(FIRST_INSERT + offset, rgb_to_fl(*rgb))

    bus = index_of("VOX BUS")
    for name, _, role in LAYOUT:
        if role != "vocal":
            continue
        track = index_of(name)
        mixer.setRouteTo(track, bus, True)
        mixer.setRouteTo(track, MASTER, False)   # the bus feeds Master; avoid the vocal being counted twice
        for fx_name, level in SEND_LEVELS.items():
            fx = index_of(fx_name)
            mixer.setRouteTo(track, fx, True)
            try:
                mixer.setRouteToLevel(track, fx, level)
            except AttributeError:
                print("Vocal Session Setup: this FL version cannot set send levels (needs API 36+); "
                      "set the send knobs by hand")
    mixer.afterRoutingChanged()

    arm = index_of(ARM_TRACK)
    if not mixer.isTrackArmed(arm):
        mixer.armTrack(arm)
    print("Vocal Session Setup: done. Now pick the input on '%s', load your vocal chain, and record." % ARM_TRACK)
    for hint in HINTS:
        print("  - " + hint)
    return True


def slot_plugin_names(track_index):
    """Names of the plugins loaded in the slots of one mixer track (empty slots are skipped)."""
    names = []
    for slot in range(MAX_SLOTS):
        if plugins.isValid(track_index, slot):
            names.append(plugins.getPluginName(track_index, slot))
    return names


def audit():
    """Print and return {track name: {"plugins": [...], "missing": [...]}} for the tracks in EXPECTED."""
    if plugins is None:
        print("Vocal Session Setup: this FL version has no plugins module; cannot audit")
        return {}
    report = {}
    for track_name, groups in EXPECTED.items():
        index = MASTER if track_name == MASTER_NAME else index_of(track_name)
        loaded = slot_plugin_names(index)
        lowered = [n.lower() for n in loaded]
        missing = ["/".join(g) for g in groups if not any(alt in n for alt in g for n in lowered)]
        report[track_name] = {"plugins": loaded, "missing": missing}
        status = "OK     " if not missing else "MISSING"
        print("Vocal chain %s %-9s [%s]%s" % (status, track_name, ", ".join(loaded) or "empty",
                                              ("  load: " + ", ".join(missing)) if missing else ""))
    return report


def OnNoteOn(event):
    if event.data2 <= 0:
        return
    if event.data1 == SETUP_NOTE:
        setup()
        event.handled = True
    elif event.data1 == AUDIT_NOTE:
        audit()
        event.handled = True
''',

# ======== embedded verbatim from fl-studio/device_PluginProbe.py ========
'PluginProbe': r'''# name: Plugin Probe
"""FL Studio MIDI-controller script: READ-ONLY. Lists every plugin loaded in your mixer slots and the parameters
FL can see on each, so you know exactly what can be automated (Nectar 4, Ozone 12, Unison Mangler, ...).

Press PROBE_NOTE (default 124 = E10 in FL's note names) on the assigned MIDI input. Output goes to View > Script output:

    track 0 (Master) slot 0: Ozone 12   (57 params)
        [0] Bypass = 0.0
        [1] Output Gain = 0.5
        ...

Why: FL's scripting API can read and set the *normalised* value of any parameter a plugin exposes to the host, but
each plugin decides which parameters it exposes and what they are called. iZotope plugins, Unison plugins and
others differ, and I could not find those lists published. Run this once with your chain loaded, send me the output,
and specific parameters can be wired into automation from real names instead of guesses.

Nothing is written to FL: no parameter, preset or routing is changed. (API: plugins.isValid / getPluginName /
getParamCount / getParamName / getParamValue / getParamValueString, mixer.trackCount / getTrackName.)
Tested against stubs of the FL modules, not inside FL Studio.
"""
import mixer
import plugins

PROBE_NOTE = 124
MAX_SLOTS = 10
FIRST_TRACK = 0            # 0 is the Master
LAST_TRACK = 32            # probe tracks FIRST_TRACK..LAST_TRACK
MAX_PARAMS_PRINTED = 80    # per plugin (many plugins expose hundreds of unnamed parameters)


def describe_param(track, slot, param):
    name = plugins.getParamName(param, track, slot)
    value = plugins.getParamValue(param, track, slot)
    try:
        shown = plugins.getParamValueString(param, track, slot)
    except Exception:  # only some plugins support value strings
        shown = ""
    return name, value, shown


def probe():
    """Return [(track, slot, plugin name, [(param index, name, value, value string), ...]), ...] and print it."""
    results = []
    last = min(LAST_TRACK, mixer.trackCount() - 1)
    for track in range(FIRST_TRACK, last + 1):
        for slot in range(MAX_SLOTS):
            if not plugins.isValid(track, slot):
                continue
            count = plugins.getParamCount(track, slot)
            params = []
            for param in range(min(count, MAX_PARAMS_PRINTED)):
                name, value, shown = describe_param(track, slot, param)
                if name:
                    params.append((param, name, value, shown))
            title = plugins.getPluginName(track, slot)
            results.append((track, slot, title, params))
            print("track %d (%s) slot %d: %s   (%d params exposed)" % (track, mixer.getTrackName(track), slot, title, count))
            for param, name, value, shown in params:
                print("    [%d] %s = %.3f%s" % (param, name, value, ("  (" + shown + ")") if shown else ""))
            if count > MAX_PARAMS_PRINTED:
                print("    ... %d more" % (count - MAX_PARAMS_PRINTED))
    if not results:
        print("Plugin Probe: no plugins found in mixer slots %d-%d" % (FIRST_TRACK, last))
    return results


def OnNoteOn(event):
    if event.data1 == PROBE_NOTE and event.data2 > 0:
        probe()
        event.handled = True
''',

# ======== embedded verbatim from fl-studio/device_PinkTheme.py ========
'PinkTheme': r'''# name: Pink Theme Painter
"""FL Studio MIDI-controller script: paints every row in a pink / purple / red / black palette, pink dominant.

What it colours (all through documented FL scripting calls):
    channel rack rows      channels.setChannelColor
    mixer inserts          mixer.setTrackColor
    playlist tracks        playlist.setTrackColor
    patterns               patterns.setPatternColor

Every row gets the next colour of a 10-colour cycle (6 pinks, 2 purples, 1 red, 1 near-black), and no two
neighbouring rows share a colour, so the rack reads as different-coloured stripes with pink in charge.
It paints once when the script starts, then again for any channel or pattern you add afterwards. Rows you
already have keep whatever colour you give them by hand until you repaint (see REPAINT_NOTE).

Setup: copy to  Documents/Image-Line/FL Studio/Settings/Hardware/PinkTheme/device_PinkTheme.py , then in
Options > MIDI Settings pick "Pink Theme Painter" as the controller type for any MIDI input (it does not
need a keyboard; assign it to any port). Script output appears in View > Script output.

What this can NOT do: change FL's own UI colours (Hue / Selection / Highlight / Steps / note colours). Those
live in Options > Theme (F10); docs/06-pink-theme.md lists the exact values to enter. I found nothing in
FL's scripting API or manual for recolouring the piano roll's keyboard keys themselves.

Colour format: FL uses 0x--BBGGRR. Tested against stubs of the FL modules, not inside FL Studio.
"""
import channels
import mixer
import patterns
import playlist

# name -> (r, g, b)
COLORS = {
    "hot_pink": (255, 20, 147),
    "neon_pink": (255, 77, 166),
    "magenta_pink": (233, 30, 140),
    "light_pink": (255, 158, 210),
    "purple": (155, 48, 255),
    "deep_purple": (91, 33, 182),
    "red": (224, 30, 75),
    "black": (46, 34, 51),  # dark plum, so the row stays visible on FL's dark UI
}
CYCLE = ["hot_pink", "neon_pink", "purple", "magenta_pink", "red",
         "light_pink", "black", "hot_pink", "deep_purple", "neon_pink"]
PINKS = {"hot_pink", "neon_pink", "magenta_pink", "light_pink"}

MAX_MIXER_INSERTS = 64      # paint at most this many inserts (index 1 upwards)
PLAYLIST_TRACKS = 64        # paint playlist tracks 1..N (FL has 500)
MASTER_COLOR = "hot_pink"   # mixer master track
REPAINT_NOTE = None         # set to a MIDI note number (e.g. 127) to repaint everything when it is pressed
PAINT_ON_START = True       # False: leave existing colours alone at start-up (new channels/patterns still get painted)
IDLE_CHECK_EVERY = 20       # OnIdle calls between "did anything get added?" checks


def rgb_to_fl(r, g, b):
    """FL colour integer (0x--BBGGRR)."""
    return (b << 16) | (g << 8) | r


def color_for(index):
    """FL colour for the row at `index` (0-based) in the repeating cycle."""
    return rgb_to_fl(*COLORS[CYCLE[index % len(CYCLE)]])


def set_channel_color(index, color):
    try:
        channels.setChannelColor(index, color, True)   # useGlobalIndex needs API 33+
    except TypeError:
        channels.setChannelColor(index, color)


def paint_channels(start=0):
    total = channels.channelCount(1)
    for i in range(start, total):
        set_channel_color(i, color_for(i))
    return total


def paint_mixer():
    mixer.setTrackColor(0, rgb_to_fl(*COLORS[MASTER_COLOR]))
    last_insert = max(mixer.trackCount() - 2, 0)   # trackCount includes master (0) and the utility "Current" track
    for i in range(1, min(last_insert, MAX_MIXER_INSERTS) + 1):
        mixer.setTrackColor(i, color_for(i - 1))


def paint_playlist():
    for i in range(1, PLAYLIST_TRACKS + 1):
        playlist.setTrackColor(i, color_for(i - 1))


def paint_patterns(start=1):
    total = patterns.patternCount()
    for i in range(start, total + 1):
        patterns.setPatternColor(i, color_for(i - 1))
    return total


_state = {"channels": 0, "patterns": 0, "idle": 0}


def paint_all():
    _state["channels"] = paint_channels()
    paint_mixer()
    paint_playlist()
    _state["patterns"] = paint_patterns()
    print("Pink Theme Painter: painted %d channels, %d patterns" % (_state["channels"], _state["patterns"]))


def OnInit():
    # FL may call OnInit again on a script it kept in memory (see the callbacks docs), so start from a clean state.
    _state.update(channels=0, patterns=0, idle=0)
    if PAINT_ON_START:
        paint_all()
    else:  # remember what exists now so OnIdle only paints what is added later
        _state["channels"] = channels.channelCount(1)
        _state["patterns"] = patterns.patternCount()


def OnIdle():
    _state["idle"] += 1
    if _state["idle"] % IDLE_CHECK_EVERY:
        return
    channel_total = channels.channelCount(1)
    if channel_total > _state["channels"]:          # only paint what was added; never touch older rows
        paint_channels(_state["channels"])
    _state["channels"] = channel_total
    pattern_total = patterns.patternCount()
    if pattern_total > _state["patterns"]:
        paint_patterns(_state["patterns"] + 1)
    _state["patterns"] = pattern_total


def OnNoteOn(event):
    if REPAINT_NOTE is not None and event.data1 == REPAINT_NOTE and event.data2 > 0:
        paint_all()
        event.handled = True
''',
}

_modules = {}      # part name -> loaded module (only enabled parts that loaded)
_pending = {}      # guarded note -> time of its first press
_reported = set()  # (part, callback) pairs already reported as failing, so OnIdle cannot flood the output


def _log(message):
    print("Trap Metal Kit: " + message)


def _load_all():
    _modules.clear()
    for name in ENABLED:
        if name not in SECTION_ORDER:
            _log("ENABLED has an unknown part '%s' (known: %s); ignored" % (name, ", ".join(SECTION_ORDER)))
    for name in OVERRIDES:
        if name not in SECTION_ORDER:
            _log("OVERRIDES has an unknown part '%s' (known: %s); ignored" % (name, ", ".join(SECTION_ORDER)))
    for name in SECTION_ORDER:
        if not ENABLED.get(name, True):
            continue
        filename = "device_%s.py" % name
        try:
            module = types.ModuleType("device_" + name)
            module.__file__ = filename
            exec(compile(_SOURCES[name], filename, "exec"), module.__dict__)
            for key, value in OVERRIDES.get(name, {}).items():
                if hasattr(module, key):
                    setattr(module, key, value)
                else:
                    _log("OVERRIDES: %s has no setting called '%s' (typo?); ignored" % (name, key))
            _modules[name] = module
        except Exception:
            _log("%s could not be loaded and is switched off:\n%s" % (name, traceback.format_exc()))


def _call(callback, *args):
    """Run `callback` on every loaded part that defines it, stopping once one marks the event handled."""
    for name in SECTION_ORDER:
        module = _modules.get(name)
        handler = getattr(module, callback, None) if module is not None else None
        if handler is None:
            continue
        try:
            handler(*args)
        except Exception:
            if (name, callback) not in _reported:
                _reported.add((name, callback))
                _log("%s.%s failed (the other parts keep working; reported once):\n%s"
                     % (name, callback, traceback.format_exc()))
            continue
        if args and getattr(args[0], "handled", False):
            return True
    return False


def claims():
    """Which notes and mixer inserts each loaded part uses: ({note: [who, ...]}, {insert: [who, ...]})."""
    notes, inserts = {}, {}

    def claim(table, key, who):
        table.setdefault(key, []).append(who)

    dj = _modules.get("TrapDJ")
    if dj is not None:
        for note in range(dj.FIRST_NOTE, dj.stop_first_note() + dj.ROWS):
            claim(notes, note, "TrapDJ")
        if dj.XFADE_CC is not None:
            for insert in (dj.DECK_A_MIXER, dj.DECK_B_MIXER):
                claim(inserts, insert, "TrapDJ crossfader")
    vocal = _modules.get("VocalSetup")
    if vocal is not None:
        claim(notes, vocal.SETUP_NOTE, "VocalSetup SETUP")
        claim(notes, vocal.AUDIT_NOTE, "VocalSetup AUDIT")
        for insert in range(vocal.FIRST_INSERT, vocal.FIRST_INSERT + len(vocal.LAYOUT)):
            claim(inserts, insert, "VocalSetup layout")
    probe = _modules.get("PluginProbe")
    if probe is not None:
        claim(notes, probe.PROBE_NOTE, "PluginProbe PROBE")
    theme = _modules.get("PinkTheme")
    if theme is not None and theme.REPAINT_NOTE is not None:
        claim(notes, theme.REPAINT_NOTE, "PinkTheme REPAINT")
    return notes, inserts


def find_conflicts():
    """Human-readable lines for any note or mixer insert that two parts both want."""
    notes, inserts = claims()
    lines = []
    for note, who in sorted(notes.items()):
        if len(who) > 1:
            lines.append("note %d is claimed by %s" % (note, " and ".join(who)))
    for insert, who in sorted(inserts.items()):
        if len(who) > 1:
            lines.append("mixer insert %d is used by %s" % (insert, " and ".join(who)))
    return lines


def _command_notes():
    notes = set()
    for name, (setting, _) in GUARDED.items():
        module = _modules.get(name)
        if module is not None and getattr(module, setting, None) is not None:
            notes.add(getattr(module, setting))
    for name, setting in (("VocalSetup", "AUDIT_NOTE"), ("PluginProbe", "PROBE_NOTE")):
        module = _modules.get(name)
        if module is not None:
            notes.add(getattr(module, setting))
    return notes


def _guard(event):
    """True if `event` is a guarded key pressed for the first time: swallow it and wait for the second press."""
    if not CONFIRM_SECONDS or event.data2 <= 0:
        return False
    for name, (setting, what) in GUARDED.items():
        module = _modules.get(name)
        if module is None or getattr(module, setting, None) != event.data1:
            continue
        now = time.time()
        first = _pending.get(event.data1)
        if first is not None and now - first <= CONFIRM_SECONDS:
            del _pending[event.data1]
            return False
        _pending[event.data1] = now
        _log("press note %d again within %g seconds to %s" % (event.data1, CONFIRM_SECONDS, what))
        event.handled = True
        return True
    return False


def describe():
    """The active key map as lines of text."""
    lines = []
    dj = _modules.get("TrapDJ")
    if dj is not None:
        stop = dj.stop_first_note()
        line = "notes %d-%d launch clips (%d decks x %d), %d-%d stop decks" % (
            dj.FIRST_NOTE, stop - 1, dj.ROWS, dj.COLUMNS, stop, stop + dj.ROWS - 1)
        if dj.XFADE_CC is not None:
            line += "; CC %d crossfades mixer inserts %d and %d" % (dj.XFADE_CC, dj.DECK_A_MIXER, dj.DECK_B_MIXER)
        lines.append(line)
    probe = _modules.get("PluginProbe")
    if probe is not None:
        lines.append("note %d lists every plugin and parameter" % probe.PROBE_NOTE)
    vocal = _modules.get("VocalSetup")
    if vocal is not None:
        lines.append("note %d audits the vocal chain; note %d builds the vocal mixer" % (vocal.AUDIT_NOTE, vocal.SETUP_NOTE))
    theme = _modules.get("PinkTheme")
    if theme is not None and theme.REPAINT_NOTE is not None:
        lines.append("note %d repaints everything pink" % theme.REPAINT_NOTE)
    return lines


_load_all()


def OnInit():
    _pending.clear()
    _reported.clear()
    _log("ready (build %s). Parts on: %s" % (BUILD, ", ".join(n for n in SECTION_ORDER if n in _modules) or "none"))
    for line in describe():
        _log("  " + line)
    if CONFIRM_SECONDS:
        _log("  keys that change your project need a second press within %g s" % CONFIRM_SECONDS)
    for line in find_conflicts():
        _log("WARNING: " + line + " - change one in CONFIG so they do not fight")
    _call("OnInit")


def OnDeInit():
    _call("OnDeInit")


def OnIdle():
    _call("OnIdle")


def OnNoteOn(event):
    if _guard(event):
        return
    _call("OnNoteOn", event)


def OnNoteOff(event):
    _call("OnNoteOff", event)
    if not event.handled and event.data1 in _command_notes():
        event.handled = True    # the release of a command key should not reach the channel rack either


def OnControlChange(event):
    _call("OnControlChange", event)
